## Code alongs merging

In [6]:
import pandas as pd
import numpy as np

# Matriser
# np.arange(16)  -> Matris 1D array
np.arange(16).reshape(4, 4 ) # .reshape(rows, columns) makes it 2D.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.zeros((3,4))  # Ger en ut en ny array med bara nollor 3x4 matris. (2D array 3x4 shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((4,3)) # Kan göra samma fast med 1:or

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# Man kan skapa olika DataFrames av arrayesen vi skapat ovanför

df1 =pd.DataFrame(np.arange(16).reshape(4, 4), columns = list("ABCD")) # Gjort om en np 2D array -> DF, serieobjekt, varje kolumn är en serie
df1

A   B   C   D
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [18]:
df2 = pd.DataFrame(np.zeros((3,4)), columns=list("ABCD"))
df2

A    B    C    D
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0

In [19]:
# Samma igen, enda skillnaden är en annan index

df3 = pd.DataFrame(np.ones((4,3)), index = [1,5,10,15])
df3

0    1    2
1   1.0  1.0  1.0
5   1.0  1.0  1.0
10  1.0  1.0  1.0
15  1.0  1.0  1.0

----------------------------
## Concat - Concatination, slå ihop

- concatenates pandas objects along an axis(rows, columns)
- there are different "mängd logics" set logics (ex -> inner outer, left, right)
- pd.concat -> outer join by default

In [20]:
df1, df2

(    A   B   C   D
 0   0   1   2   3
 1   4   5   6   7
 2   8   9  10  11
 3  12  13  14  15,
      A    B    C    D
 0  0.0  0.0  0.0  0.0
 1  0.0  0.0  0.0  0.0
 2  0.0  0.0  0.0  0.0)

In [ ]:
# Det blir en lista [] för den vill ha en "iterable" om man hoovrar över concat
pd.concat([df1, df2], axis = 0)


In [23]:
# Puts all cols from df1 and then all cols from df2
# Those indices that are missing in one df is filled with NaNs
pd.concat([df1, df2], axis = "columns") 
# Vi har index 0,1,2 på df2 vi har inte index 3
# Vi ser på index 3 att vi har NaN värden
# Vi ser att när vi kör axis = "columns" att den slår ihop alla kolumner på första dfet och alla kolumn på andra df


A   B   C   D    A    B    C    D
0   0   1   2   3  0.0  0.0  0.0  0.0
1   4   5   6   7  0.0  0.0  0.0  0.0
2   8   9  10  11  0.0  0.0  0.0  0.0
3  12  13  14  15  NaN  NaN  NaN  NaN

In [24]:
df1, df3 
# We can see that index 1 är gemensamt, resten är ogemensamt

(    A   B   C   D
 0   0   1   2   3
 1   4   5   6   7
 2   8   9  10  11
 3  12  13  14  15,
       0    1    2
 1   1.0  1.0  1.0
 5   1.0  1.0  1.0
 10  1.0  1.0  1.0
 15  1.0  1.0  1.0)

In [25]:
# slår ihop i axis rows, df1 rows first then f2 rows, NaNs are used for missing values
pd.concat([df1, df3])

A     B     C     D    0    1    2
0    0.0   1.0   2.0   3.0  NaN  NaN  NaN
1    4.0   5.0   6.0   7.0  NaN  NaN  NaN
2    8.0   9.0  10.0  11.0  NaN  NaN  NaN
3   12.0  13.0  14.0  15.0  NaN  NaN  NaN
1    NaN   NaN   NaN   NaN  1.0  1.0  1.0
5    NaN   NaN   NaN   NaN  1.0  1.0  1.0
10   NaN   NaN   NaN   NaN  1.0  1.0  1.0
15   NaN   NaN   NaN   NaN  1.0  1.0  1.0

In [28]:
# per default: outer join
pd.concat([df1, df3], axis = "rows")

# Vi kan se att den indexen som var gemensam slås ihop, resten fylls med NaNs

A     B     C     D    0    1    2
0    0.0   1.0   2.0   3.0  NaN  NaN  NaN
1    4.0   5.0   6.0   7.0  NaN  NaN  NaN
2    8.0   9.0  10.0  11.0  NaN  NaN  NaN
3   12.0  13.0  14.0  15.0  NaN  NaN  NaN
1    NaN   NaN   NaN   NaN  1.0  1.0  1.0
5    NaN   NaN   NaN   NaN  1.0  1.0  1.0
10   NaN   NaN   NaN   NaN  1.0  1.0  1.0
15   NaN   NaN   NaN   NaN  1.0  1.0  1.0

In [27]:
# intersection(snitt) between df1 nd df2 on the indices
pd.concat([df1, df3], axis = "columns", join = "inner")

A  B  C  D    0    1    2
1  4  5  6  7  1.0  1.0  1.0

----------------
## Merge

In [30]:
left = pd.DataFrame(
    {
        "key": ["K0", "K0", "K1", "K2"],
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
    }
)

# en keys(nyckel)= column, sedan en lista kommer bli en Serie(1D df)

right = pd.DataFrame(
    {
        "key": ["K0", "K1", "K2", "K3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    }
)

left, right

(  key   A   B
 0  K0  A0  B0
 1  K0  A1  B1
 2  K1  A2  B2
 3  K2  A3  B3,
   key   C   D
 0  K0  C0  D0
 1  K1  C1  D1
 2  K2  C2  D2
 3  K3  C3  D3)

In [33]:
# Syntax with function

# Vi kan merga left, right
# Vi väljer på vilken vi ska merga på (key)

# inner join -> K3 from right not included because we have choosen only keys that are the same
pd.merge(left, right, on = "key", indicator=True) # 2 olika df
# Indicator lets us know if we have merged from right or left


key   A   B   C   D _merge
0  K0  A0  B0  C0  D0   both
1  K0  A1  B1  C0  D0   both
2  K1  A2  B2  C1  D1   both
3  K2  A3  B3  C2  D2   both

In [35]:
# we can do a method instead of the function merge, syntax with method
# note that left does not have a K3, so in row index 4 only merge from right
left.merge(right, on = "key", how ="outer", indicator=True)

key    A    B   C   D      _merge
0  K0   A0   B0  C0  D0        both
1  K0   A1   B1  C0  D0        both
2  K1   A2   B2  C1  D1        both
3  K2   A3   B3  C2  D2        both
4  K3  NaN  NaN  C3  D3  right_only

In [36]:
right

key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [38]:
# Vi gör en ny left and right, ser lite annorlunda ut
left = pd.DataFrame(
    {
        "key1": ["K0", "K0", "K1", "K2"],
        "key2": ["K0", "K1", "K0", "K1"],
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
    }
)

right = pd.DataFrame(
    {
        "key1": ["K0", "K1", "K1", "K2"],
        "key2": ["K0", "K0", "K0", "K0"],
        "A": ["A0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    }
)

left, right

(  key1 key2   A   B
 0   K0   K0  A0  B0
 1   K0   K1  A1  B1
 2   K1   K0  A2  B2
 3   K2   K1  A3  B3,
   key1 key2   A   D
 0   K0   K0  A0  D0
 1   K1   K0  C1  D1
 2   K1   K0  C2  D2
 3   K2   K0  C3  D3)

In [41]:
# Vi har två st keys som är samma. 
# Vi vill mergea på key 1 och key 2
# Vill kolla vad som händer med A kolumnen(givetvis de andra också)

# merge on both key1 and key2 columns, and an inner join - intersection
left.merge(right, on = ["key1", "key2"], indicator=True)


key1 key2 A_x   B A_y   D _merge
0   K0   K0  A0  B0  A0  D0   both
1   K1   K0  A2  B2  C1  D1   both
2   K1   K0  A2  B2  C2  D2   both

In [43]:
left, right

(  key1 key2   A   B
 0   K0   K0  A0  B0
 1   K0   K1  A1  B1
 2   K1   K0  A2  B2
 3   K2   K1  A3  B3,
   key1 key2   A   D
 0   K0   K0  A0  D0
 1   K1   K0  C1  D1
 2   K1   K0  C2  D2
 3   K2   K0  C3  D3)

In [42]:

# Merging på vänstra
# A_x = vänstra, A_y = högra
left.merge(right, on = ["key1", "key2"], indicator=True, how = "left")

key1 key2 A_x   B  A_y    D     _merge
0   K0   K0  A0  B0   A0   D0       both
1   K0   K1  A1  B1  NaN  NaN  left_only
2   K1   K0  A2  B2   C1   D1       both
3   K1   K0  A2  B2   C2   D2       both
4   K2   K1  A3  B3  NaN  NaN  left_only

In [45]:
left.merge(right, on = ["key1", "key2"], indicator=True, how = "right", suffixes=["_left", "_right"])

key1 key2 A_left    B A_right   D      _merge
0   K0   K0     A0   B0      A0  D0        both
1   K1   K0     A2   B2      C1  D1        both
2   K1   K0     A2   B2      C2  D2        both
3   K2   K0    NaN  NaN      C3  D3  right_only

-----------------
## Join

- uses merge internally
- combines columns

In [47]:
left = pd.DataFrame(
    {"A": ["A0", "A1", "A2"], "B": ["B0", "B1", "B2"]}, index=["K0", "K1", "K2"]
)


right = pd.DataFrame(
    {"C": ["C0", "C2", "C3"], "D": ["D0", "D2", "D3"]}, index=["K0", "K2", "K3"]
)

left, right

# Vi har en index som är annorlunda K3(högra) och K1(vänstra) skiljer sig åt

(     A   B
 K0  A0  B0
 K1  A1  B1
 K2  A2  B2,
      C   D
 K0  C0  D0
 K2  C2  D2
 K3  C3  D3)

In [50]:
# Note we join on K1 which only exists in left -> so this is a left join(joinar på vänstra df)
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [51]:
# indices from right -> right join
left.join(right, how = "right") 

A    B   C   D
K0   A0   B0  C0  D0
K2   A2   B2  C2  D2
K3  NaN  NaN  C3  D3

## Webscraping HTML tables

In [52]:
# Mål är att kunna skrapa och skapa en DF från data på webben
# Vi installerar i pipenv install requests, html5lib, bs4, lxml

pd.read_html("https://en.wikipedia.org/wiki/FIFA") 

ImportError: lxml not found, please install it