## Code alongs merging

In [6]:
import pandas as pd
import numpy as np

# Matriser
# np.arange(16)  -> Matris 1D array
np.arange(16).reshape(4, 4 ) # .reshape(rows, columns) makes it 2D.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.zeros((3,4))  # Ger en ut en ny array med bara nollor 3x4 matris. (2D array 3x4 shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((4,3)) # Kan göra samma fast med 1:or

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# Man kan skapa olika DataFrames av arrayesen vi skapat ovanför

df1 =pd.DataFrame(np.arange(16).reshape(4, 4), columns = list("ABCD")) # Gjort om en np 2D array -> DF, serieobjekt, varje kolumn är en serie
df1

A   B   C   D
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [18]:
df2 = pd.DataFrame(np.zeros((3,4)), columns=list("ABCD"))
df2

A    B    C    D
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0

In [19]:
# Samma igen, enda skillnaden är en annan index

df3 = pd.DataFrame(np.ones((4,3)), index = [1,5,10,15])
df3

0    1    2
1   1.0  1.0  1.0
5   1.0  1.0  1.0
10  1.0  1.0  1.0
15  1.0  1.0  1.0

----------------------------
## Concat - Concatination, slå ihop

- concatenates pandas objects along an axis(rows, columns)
- there are different "mängd logics" set logics (ex -> inner outer, left, right)
- pd.concat -> outer join by default

In [20]:
df1, df2

(    A   B   C   D
 0   0   1   2   3
 1   4   5   6   7
 2   8   9  10  11
 3  12  13  14  15,
      A    B    C    D
 0  0.0  0.0  0.0  0.0
 1  0.0  0.0  0.0  0.0
 2  0.0  0.0  0.0  0.0)

In [ ]:
# Det blir en lista [] för den vill ha en "iterable" om man hoovrar över concat
pd.concat([df1, df2], axis = 0)


In [23]:
# Puts all cols from df1 and then all cols from df2
# Those indices that are missing in one df is filled with NaNs
pd.concat([df1, df2], axis = "columns") 
# Vi har index 0,1,2 på df2 vi har inte index 3
# Vi ser på index 3 att vi har NaN värden
# Vi ser att när vi kör axis = "columns" att den slår ihop alla kolumner på första dfet och alla kolumn på andra df


A   B   C   D    A    B    C    D
0   0   1   2   3  0.0  0.0  0.0  0.0
1   4   5   6   7  0.0  0.0  0.0  0.0
2   8   9  10  11  0.0  0.0  0.0  0.0
3  12  13  14  15  NaN  NaN  NaN  NaN

In [24]:
df1, df3 
# We can see that index 1 är gemensamt, resten är ogemensamt

(    A   B   C   D
 0   0   1   2   3
 1   4   5   6   7
 2   8   9  10  11
 3  12  13  14  15,
       0    1    2
 1   1.0  1.0  1.0
 5   1.0  1.0  1.0
 10  1.0  1.0  1.0
 15  1.0  1.0  1.0)

In [25]:
# slår ihop i axis rows, df1 rows first then f2 rows, NaNs are used for missing values
pd.concat([df1, df3])

A     B     C     D    0    1    2
0    0.0   1.0   2.0   3.0  NaN  NaN  NaN
1    4.0   5.0   6.0   7.0  NaN  NaN  NaN
2    8.0   9.0  10.0  11.0  NaN  NaN  NaN
3   12.0  13.0  14.0  15.0  NaN  NaN  NaN
1    NaN   NaN   NaN   NaN  1.0  1.0  1.0
5    NaN   NaN   NaN   NaN  1.0  1.0  1.0
10   NaN   NaN   NaN   NaN  1.0  1.0  1.0
15   NaN   NaN   NaN   NaN  1.0  1.0  1.0

In [28]:
# per default: outer join
pd.concat([df1, df3], axis = "rows")

# Vi kan se att den indexen som var gemensam slås ihop, resten fylls med NaNs

A     B     C     D    0    1    2
0    0.0   1.0   2.0   3.0  NaN  NaN  NaN
1    4.0   5.0   6.0   7.0  NaN  NaN  NaN
2    8.0   9.0  10.0  11.0  NaN  NaN  NaN
3   12.0  13.0  14.0  15.0  NaN  NaN  NaN
1    NaN   NaN   NaN   NaN  1.0  1.0  1.0
5    NaN   NaN   NaN   NaN  1.0  1.0  1.0
10   NaN   NaN   NaN   NaN  1.0  1.0  1.0
15   NaN   NaN   NaN   NaN  1.0  1.0  1.0

In [27]:
# intersection(snitt) between df1 nd df2 on the indices
pd.concat([df1, df3], axis = "columns", join = "inner")

A  B  C  D    0    1    2
1  4  5  6  7  1.0  1.0  1.0